# This workflow runs the test suites with different versions of python
name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.10.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get install -y xvfb x3270 locales xterm
        python -m pip install -r requirements-dev.txt

    - name: Lint
      run: |
        inv lint

    - name: Run utests
      run: |
        inv utest

    - name: Run atests
      run: |
        sudo locale-gen en_US
        LANG=en_US.iso88591 xvfb-run robot --exclude no-ci --loglevel DEBUG atest/

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Tests results python${{ matrix.python-version }}
        path: |
          log.html
          report.html
          output.xml
