# This workflow runs the test suites with different versions of python
name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.10.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get install -y xvfb x3270 locales xterm
        python -m pip install -r requirements-dev.txt

    - name: Lint
      run: |
        inv lint

    - name: Run utests with coverage
      run: |
        coverage run --branch --source Mainframe3270/ -m pytest --verbose utest/
        coverage report
        coverage xml

    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
        flags: unit
        move_coverage_to_trash: true

    - name: Run atests with coverage
      run: |
        sudo locale-gen en_US
        LANG=en_US.iso88591 xvfb-run coverage run --branch --source Mainframe3270/ -m robot --exclude no-ci --loglevel DEBUG atest/
        coverage report
        coverage xml

    - name: Upload acceptance tests coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
        flags: acceptance

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Tests results python${{ matrix.python-version }}
        path: |
          log.html
          report.html
          output.xml
